const Config = {
    // Boss settings
    BOSS_SPEED: 120,
    BOSS_SIZE: 80,
    BOSS_COLOR: 0x666666,
    BOSS_ATTACK_COLOR: 0xff0000,
    BOSS_ATTACK_WINDUP_MS: 1000,
    BOSS_ATTACK_WINDUP_COLOR: 0xffaa00,
    BOSS_ATTACK_DURATION_MS: 500,
    BOSS_ATTACK_COOLDOWN_MS: 1000,
    BOSS_ATTACK_DAMAGE: 10,
    BOSS_HURT_DURATION_MS: 1000,
    BOSS_HURT_COLOR: 0x0066ff,
    BOSS_KNOCKBACK_VELOCITY: 200,
    BOSS_MAX_HEALTH: 100,
    BOSS_HURT_DAMAGE: 10,

    HORNET_WALK_SPEED: 200,
    HORNET_JUMP_VELOCITY: -400,
    HORNET_GRAVITY: 500,
    HORNET_BOUNCE: 0.1,
    GROUND_Y: 570,

    DASH_FORCE_X: 600,
    DASH_DURATION_MS: 300,
    DASH_COOLDOWN_MS: 800,
    DASH_AIR_FORCE_X: 550,
    DASH_AIR_DURATION_MS: 250,

    ATTACK_DURATION_MS: 250,
    ATTACK_HITBOX_WIDTH: 120,
    ATTACK_HITBOX_HEIGHT: 80,
    ATTACK_DAMAGE: 10,

    HORNET_MAX_HEALTH: 100,
    INVINCIBILITY_DURATION_MS: 1500,

    ANIM_IDLE_FRAMERATE: 8,
    ANIM_RUN_FRAMERATE: 8,
    ANIM_JUMP_FRAMERATE: 8,
    ANIM_DASH_FRAMERATE: 12,
    ANIM_ATTACK_FRAMERATE: 12,

    GLOW_TINT_TOP_LEFT: 0xffffff,
    GLOW_TINT_TOP_RIGHT: 0xffcc88,
    GLOW_TINT_BOTTOM_LEFT: 0xffffff,
    GLOW_TINT_BOTTOM_RIGHT: 0xff7722
};
